name: Pipeline CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 11 * * *'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test > relatorio-validacao-login.txt

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-validacao-login
          path: relatorio-validacao-login.txt